name: AI Scanner 24/7

on:
  workflow_dispatch:

  schedule:
    - cron: "*/5 * * * *"

jobs:
  scanner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Packages
        run: |
          pip install pandas yfinance

      - name: Run Scanner
        run: |
          python scripts/run_scanner.py

      - name: Copy JSON
        run: |
          cp data/live_data.json dashboard-next/public/live_data.json

      - name: Commit Files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add .

          git commit -m "auto update" || echo "nothing to commit"

          git push